> rustresult Err:
RustlikeResult {
  _type: 'err',
  _value: undefined,
  _error: 'error message'
}

> neverthrow err:
Err { error: 'error message' }

> effect Effect.fail:
{
  _id: 'Exit',
  _tag: 'Failure',
  cause: { _id: 'Cause', _tag: 'Fail', failure: 'error message' }
}

> effect Exit.fail:
{
  _id: 'Exit',
  _tag: 'Failure',
  cause: { _id: 'Cause', _tag: 'Fail', failure: 'error message' }
}

Loop N: 100,000
┌─────────┬──────────────────────┬──────────────────────┬──────────────┬────────────────┬───────────────┬─────────┐
│ (index) │ task                 │ mean (ns)            │ median (ns)  │ mean (op/s)    │ median (op/s) │ samples │
├─────────┼──────────────────────┼──────────────────────┼──────────────┼────────────────┼───────────────┼─────────┤
│ 0       │ 'rustresult Err'     │ '396911.70 ± 0.56%'  │ '373600.01'  │ '2566 ± 0.50%' │ '2677'        │ 2520    │
│ 1       │ 'neverthrow err'     │ '272838.43 ± 0.53%'  │ '252300.02'  │ '3751 ± 0.46%' │ '3964'        │ 3666    │
│ 2       │ 'effect Effect.fail' │ '1199478.54 ± 0.99%' │ '1157300.00' │ '845 ± 0.68%'  │ '864'         │ 834     │
│ 3       │ 'effect Exit.fail'   │ '1149108.72 ± 0.57%' │ '1125799.89' │ '876 ± 0.52%'  │ '888'         │ 871     │
└─────────┴──────────────────────┴──────────────────────┴──────────────┴────────────────┴───────────────┴─────────┘
